remote_theme: jekyll-themes-cayman
plugins: - jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
title: "TIANAO LI's Homepage"
description: "Hi there! Welcome to TIANAO LI’s Homepage！"
